# Generated by Django 4.2 on 2023-04-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_contact', models.IntegerField()),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_address', models.CharField(max_length=50)),
                ('buyer_gender', models.CharField(max_length=10)),
                ('buyer_image', models.ImageField(upload_to='Images/Sellers/')),
                ('role', models.CharField(default='Buyer', editable=False, max_length=10)),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.FloatField(default=0.0)),
                ('item_image', models.ImageField(upload_to='Images/Items/')),
                ('item_description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_contact', models.IntegerField()),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_address', models.CharField(max_length=50)),
                ('seller_gender', models.CharField(max_length=10)),
                ('seller_image', models.ImageField(upload_to='Images/Sellers/')),
                ('total_earnings', models.FloatField(default=0.0)),
                ('role', models.CharField(default='Seller', editable=False, max_length=10)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_no', models.PositiveIntegerField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.buyer')),
            ],
            options={
                'db_table': 'Payment Info',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=10)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.buyer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.item')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.seller'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('bill_status', models.CharField(max_length=10)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.buyer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.order')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.seller')),
            ],
            options={
                'db_table': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', system.managers.UserManager()),
            ],
        ),
    ]
