# Generated by Django 4.2 on 2023-04-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='customuser',
            new_name='customusers',
        ),
    ]
