# Generated by Django 4.2 on 2023-04-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_customusers_order_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customuser',
            new_name='customusers',
        ),
    ]
