# Generated by Django 4.2 on 2023-04-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_rename_customusers_bill_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='customuser',
            new_name='customusers',
        ),
    ]
