# Generated by Django 4.2 on 2023-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rename_customuser_bill_customusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
