# Generated by Django 4.2 on 2023-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_bill_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified')], default='Unverified', max_length=20),
        ),
    ]
