# Generated by Django 4.2 on 2023-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_bill_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_earnings',
            field=models.FloatField(default=0.0),
        ),
    ]
