# Generated by Django 4.2 on 2023-04-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_rename_customusers_paymentinfo_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='customuser',
            new_name='customusers',
        ),
    ]
